name: Java CI with Maven and Checkstyle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Test with Maven and run Checkstyle
      run: mvn -B test
    
    - name: Upload Checkstyle XML Report
      if: always()  # This ensures the step runs even if previous steps fail
      uses: actions/upload-artifact@v4.4.3
      with:
        name: checkstyle-report
        path: target/checkstyle-result.xml

    - name: Upload Checkstyle HTML Report
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: checkstyle-report-html
        path: target/reports/checkstyle.html