name: Java CI with Maven and Checkstyle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-deploy-checkstyle-html:
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.page_url }} # references step with id: deployment

    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: configure pages
        uses: actions/configure-pages@v5.0.0
      
      - name: Test with Maven and run Checkstyle
        run: mvn -B test 

      - name: upload checkstyle artifacts
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: checkstyle-report # Name artifact tor reference later
          path: target/reports/checkstyle.html

      - name: upload pages artifacts
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: target/reports

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4.0.5

      # debug
      - name: debug checkstyle artifacts
        run: ls -R target/reports

      - name: Log deployment URL
        run: echo ${{ steps.deployment.page_url }}
